### ISSUE TITLE
Stalled torrents & login issues

### ISSUE THREAD

**Issue by bandit8623** [mafredri/asustor-qbittorrent#1] opened 2017-09-21 22:23 UTC
originally posted here -  https://github.com/qbittorrent/qBittorrent/issues/7466
also
when i click on qbittorent the login screen wont come up without me changing the port number in the browser to something different then back to the correct port and then the login screen comes up.

**Comment by mafredri** [comment] 2017-09-22 07:49
> when i click on qbittorent the login screen wont come up without me changing the port number in the browser to something different then back to the correct port and then the login screen comes up.

Make sure `Options > Web UI > Server domains:` is set to `*`. Also, do you use ADM over HTTPS? If you are, that might be the reason. There is no way to tell ADM to open the link as HTTP instead of HTTPS. You could try enabling HTTPS in qBittorrent but you will need to provide some certificates for it to do that (also under `Options > Web UI`).

Regarding the *stalled* issue, would you mind providing me with all the settings under the following categories:

- Downloads > Hard disk
- Connection > Listening port
- Connection > Connection limits
- Speed > Rate limit settings
- BitTorrent > Privacy
- BitTorrent > Torrent queueing

I'm preparing to release 3.3.16 in the coming days, let's hope it fixes some of the issues if we can't resolve them here.

**Comment by bandit8623** [comment] 2017-09-22 15:04
- Downloads > Hard disk -  all boxes checked. i habe all my saved
   locations settup.  i also habe a monitor folder set. i drag a torrent file
   there and it automatically starts the download.
   - Connection > Listening port- 5277 i have set to random on startup.
   doesnt help if i set to a different port.
   - Connection > Connection- limits all set to 999
   - Speed > Rate limit settings  - only tbing limited is my upload to 320k
   but doesn't matter if i take rate limit off.
   - BitTorrent > Privacy -  all unchecked.
   - BitTorrent > Torrent queueing -    i have all torrent queuing off.
   tried turning on too and setting to high amounts. no change.

 server domain is set up properly

i had https enabled but turning off doesn't fix.  if i go right to my
qbittorent link it works. if i log into adm first and tben click qbittorent
thats when i have to change port then back to get login page. does on
Firefox too.


thanks for looking into this

**Comment by mafredri** [comment] 2017-09-23 09:54
I'm going to ask a couple of more in depth questions regarding settings, hope you manage to follow along. This is a bit like swinging in the dark, hoping to hit something though 😄.

Also, keep in mind that when trying some of these settings it's useful to:

1. Restart qBittorrent (toggle in App Central) after applying settings
2. Remove and add back a torrent to the client (e.g. select one *stalled* torrent that you do this with, you don't have to repeat for all while testing)

> Downloads > Hard disk

* Do you use different folders for save location and incomplete?
* Do both directories exist?
* Have you tried without Append `.!qB` to incomplete files?

> Connection > IP Filtering

* Do you use this feature?
* Have you checked `Apply to trackers`?

> Speed > Rate limit settings

* Is `µTP protocol` enabled, have you tried disabling it?
* Is `Apply rate limit to µTP protocol` enabled, have you tried disabling it?
* Is `Apply rate limit to transport overhead ` enabled, have you tried disabling it?

> BitTorrent > Privacy

* Is encryption mode set to `Prefer encryption`, if not, have you tried it?

**Comment by bandit8623** [comment] 2017-09-23 22:24
1. Restart qBittorrent (toggle in App Central) after applying settings  i
   have restarted the entire unoit after making changes and it comes back on
   the same all stalled except a few
   2. Remove and add back a torrent to the client (e.g. select one
*stalled* torrent
   that you do this with, you don't have to repeat for all while testing)  ive
   added new torrents and readded torrents and still shows stalled unless i
   force.

Downloads > Hard disk


   - Do you use different folders for save location and incomplete?pic
   attached[image: Inline image 1]
![saved loc](https://user-images.githubusercontent.com/9302078/30777616-4afcad66-a084-11e7-9b1e-f4967effec76.PNG)
   -
   - Do both directories exist? yes everything is placed in correct places.
    if i set to force everything uploads all good
   - Have you tried without Append .!qB to incomplete files? tried on and
   off no change.

Connection > IP Filtering


   - Do you use this feature? i dont use this
   - Have you checked Apply to trackers?

Speed > Rate limit settings


   - Is µTP protocol enabled, have you tried disabling it? tried on and off
   - Is Apply rate limit to µTP protocol enabled, have you tried disabling
   it?tried both
   - Is Apply rate limit to transport overhead enabled, have you tried
   disabling it?tried both

BitTorrent > Privacy


   - Is encryption mode set to Prefer encryption, if not, have you tried
   it? i have it set to prefer encryption.
   - [image: Inline image 2]
![encryption](https://user-images.githubusercontent.com/9302078/30777622-6f46cabc-a084-11e7-9f8f-35a0c7b45a61.PNG)

   - maybe just a glitch? on the left it shows that they are seeding but on
   the front it says stalled.  so maybe they really are available and seeding.
   just weird. when i add a new torrent when not in force mode it shows stalled then it starts downloading then after its completed it goes back to stalled.
   - [image: Inline image 3]
![stalledbut seeding](https://user-images.githubusercontent.com/9302078/30777630-7bcbbdba-a084-11e7-8402-21481807eb03.PNG)

**Comment by bandit8623** [comment] 2017-09-23 23:36
i left all my torrents on resume(showing stalled)  torrents look to be still uploading.  i had a few in the last hour change from stalled to uploading. after they stop uploading they go back to stalled.

**Comment by mafredri** [comment] 2017-09-24 07:53
Thanks for the replies, unfortunately it doesn't give me any hints as to what would be wrong 🙁. Which NAS version do you have? I'll try to get qBittorrent 3.3.16 out today so that you can test it out and if that doesn't help, I'll build you a debugging version that hopefully allows us to get to the bottom of it.

**Comment by mafredri** [comment] 2017-09-24 10:45
Alright, [v.3.3.16](https://github.com/mafredri/asustor-qbittorrent/releases/tag/v3.3.16) is out now, feel free to download and update manually via App Central in ADM.

I have a hunch with regards to the *stalled*-issue though, and it might not actually be a *problem*. I've managed to reproduce myself with torrents that stay *stalled* for a little while after resuming. I think this is related to the fact that I'm not connectable to the outside world, (e.g. no ports are open to my home network so that other torrent users can connect directly to me). So until qBittorrent manages to communicate with someone, it will stay *stalled*.

It's just a guess though, but it's the only thing I can think of that makes sense, especially considering the fact that some of your stalled torrents seed occasionally.

**Comment by mafredri** [comment] 2017-09-24 10:50
You should be able to witness this in the `Peers` tab of a *stalled* torrent. IP's will keep popping up and disappearing whilst the torrent is *stalled*, but when it finds a client it can talk to, the torrent will change from *stalled*  to *uploading*.

**Edit:** Enabling DHT and PeX under `BitTorrent > Privacy` can perhaps decrease the amount of time your torrents stay as stalled.

**Comment by mafredri** [comment] 2017-09-24 11:31
Another idea, do you use VPN or multiple network adapters? Maybe it could also be a factor with regards to the stalled torrents?

**Comment by bandit8623** [comment] 2017-09-24 12:24
i dont use a VPN.  i do have a switch between my router. ill do some
digging today. thx again for all the help.

**Comment by bandit8623** [comment] 2017-09-24 12:28
i cant enable dht since i use private trackers. unless that had changed.
but last time i checked that was a nono

On Sep 24, 2017 6:31 AM, "Mathias Fredriksson" <notifications@github.com>
wrote:

Another idea, do you use VPN or multiple network adapters? Maybe it could
also be a factor with regards to the stalled torrents?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mafredri/asustor-qbittorrent/issues/1#issuecomment-331703851>,
or mute the thread

**Comment by bandit8623** [comment] 2017-09-24 20:19
update.

i verified all ports are open to my client.  .  but like you said when not seeding they show stalled.

i do feel i found a bug.  the peers showing and disappearing is happening for me,  but im still uploading when they all disappear.  so the peers are still there just not showing up in the list.  for example currently im seeing 1 peers connected and 4 others trying to connect but dont.  all disappear and im still uploading at the full amount.  
if i select the torrent i see the peers,  then after some time i get a flicker and it auto unselects the torrent i was on , so thats why it doesnt show peers after a bit.  

right before the peers drop off i see about 6 more peers at zero transfer rate then boom they all disappear. when peers come back its the same one that was grabbing date the whole time.  seems to only allow 1 peer to download off me. i havent seen more than 1 peer since this issue.

i dont use a vpn or any other adapters.  just the gig nic card built into my AS304T  nas


im wondering if its an issue with adm 3.0  as it seemed to start when i upgraded. i updated to 3.3.14 about the same time. 

thx for the 3.3.16 update

and sorry for such a long post.  i just kept adding to this as the day went on.

**Comment by mafredri** [comment] 2017-09-25 16:41
Hmm, thanks for the details. It does seem very curious, and could very well be related to the ADM update. As far as I was told, nothing major was changed in ADM 3.0, but who knows. If you use ADM Defender, could that be the culprit?

We could take a look at the logs that qBittorrent has produced, but we won't necessarily see anything interesting from them. Here's how you can extract them:

1. Go to: `http://NAS_IP:8181/`
2. Log in
3. Change URL to: `http://NAS_IP:8181/query/getLog?normal=true&warning=true&info=true&critical=true`
4. Copy the JSON output and either paste here or send it to me via email
    * Feel free to censor parts of the output if you wish (you can e.g. use https://jsonlint.com to make it more human readable)
5. Just to be thorough, you could also export all your preferences via: `http://NAS_IP:8181/query/preferences` (repeat step 4)

**Comment by bandit8623** [comment] 2017-09-25 17:27
adm defender has allow all set,  nothing blacklisted

[settings.txt](https://github.com/mafredri/asustor-qbittorrent/files/1330284/settings.txt)
[jsonqbittorent.txt](https://github.com/mafredri/asustor-qbittorrent/files/1330283/jsonqbittorent.txt)

**Comment by mafredri** [comment] 2017-09-25 18:11
Hmm, the only interesting thing I found was

```
UPnP/NAT-PMP: Port mapping failure, message: could not map port using UPnP: unknown UPnP error (-1)
```

But that only leads to more issues related to stalled torrents, etc.

I did notice that you use port `8999` though, and maybe this could be a reason you're not seeing so many connections (it's my understanding that it's often blocked in many places). You could try something completely different, like `49000` and make sure it's forwarded on your router.

Other than this, I'm out of ideas though 😕.

**Comment by bandit8623** [comment] 2017-09-25 18:15
i can try  i use this site.  and it shows it open.  https://portchecker.co/check

what about this --
"id": 13,
	"message": "qBittorrent is successfully listening on interface 0.0.0.0 port: TCP/8999",
	"timestamp": 1506284627822,
	"type": 2
}, {
	"id": 14,
	"message": "qBittorrent is successfully listening on interface 0.0.0.0 port: TCP_SSL/4433",
	"timestamp": 1506284627825,
	"type": 2
}, {
	"id": 15,
	"message": "qBittorrent is successfully listening on interface :: port: TCP/8999",
	"timestamp": 1506284627825,
	"type": 2
says listening on interface but no interface is listed?

**Comment by bandit8623** [comment] 2017-09-28 00:28
i just installed deluge for asustor,  i dont have any issues with it.  so that rules out an adm issue.

**Comment by mafredri** [comment] 2017-12-28 02:04
Hey @bandit8623, this issue kind of dropped off the radar for me, sorry about that. I wanted to check in if you're still experiencing problems with qBittorrent. Version 4 is out now, so that might have brought about improvements.

**Comment by bandit8623** [comment] 2017-12-28 02:10
i actually tried it last week with new update.  it still shows stalled when
the torrent is not doing anything. but i don't seem to be having any issues
besides that.  just weird it shows stalled and not seeding.  thanks for
checking in.

On Dec 27, 2017 8:04 PM, "Mathias Fredriksson" <notifications@github.com>
wrote:

Hey @bandit8623 <https://github.com/bandit8623>, this issue kind of dropped
off the radar for me, sorry about that. I wanted to check in if you're
still experiencing problems with qBittorrent. Version 4 is out now, so that
might have brought about improvements.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mafredri/asustor-qbittorrent/issues/1#issuecomment-354214136>,
or mute the thread

**Comment by mafredri** [comment] 2017-12-28 12:04
Glad to hear it seems to be working. I agree that the *stalled* indication is confusing and signals to the user that something is wrong, even though it isn't 😕.

I'm going to close this since it seems to be working, but feel free to open a new issue if you notice any other problems. Enjoy the new year celebrations 🎉!

**Closed as completed by mafredri** 2017-12-28 12:04 UTC

**Comment by bandit8623** [comment] 2017-12-28 16:08
happy new year to you as well
